global:
  enabled: true
  tlsDisable: false

server:
  extraEnvironmentVars:
    GOOGLE_REGION: us-east1
    GOOGLE_PROJECT: mcp-hashipoc
    GOOGLE_APPLICATION_CREDENTIALS: /vault/userconfig/kms-creds/credentials.json
    VAULT_ADDR: https://127.0.0.1:8200
    VAULT_SKIP_VERIFY: true
    VAULT_CACERT: /vault/userconfig/vault-tls/vault_ca  

  extraVolumes:
    - type: 'secret'
      name: 'kms-creds'
    - type: 'secret'
      name: 'vault-tls'    

  image:
    repository: "vault"
    tag: "1.5.0"
    # Overrides the default Image Pull Policy
    pullPolicy: IfNotPresent      

  ha:
    enabled: true
    replicas: 3
    
    raft:  
      enabled: true  
      config: |
        ui = true
  
        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-tls/vault_crt"
          tls_key_file  = "/vault/userconfig/vault-tls/vault_key"
          tls_client_ca_file = "/vault/userconfig/vault-tls/vault_ca"
        }
  
        seal "gcpckms" {
          project     = "mcp-hashipoc"
          region      = "us-east1"
          key_ring    = "vault"
          crypto_key  = "vault-init"
        }
  
        storage "raft" {
          path = "/vault/data"
        }
ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200    
